name: C++ Code Analysis

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: clang-format and clang-tidy
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get update
      - run: sudo apt-get install -y cmake clang-format clang-tidy
      - name: clang-format
        run: find src/ -iname '*.h' -o -iname '*.cpp' -exec clang-format --dry-run --Werror {} +
      - name: Checkout Tensorflow
        uses: actions/checkout@v2
        with:
          repository: tensorflow/tensorflow
          path: tensorflow_src
      - name: generate compile_commands.json
        run: |
          mkdir build && cd build
          cmake .. -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DTENSORFLOW_SOURCE_DIR=../tensorflow_src
      - name: clang-tidy
        run: find src/ -iname '*.h' -o -iname '*.cpp' -exec clang-tidy --warnings-as-errors='*' -p build {} +
